version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: estoque-backend
    restart: always
    volumes:
      - ./planilhas:/app/planilhas
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.estoque.guvito.site`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: estoque-frontend
    restart: always
    environment:
      - VITE_BACKEND_URL=/api
    expose:
      - 80
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.estoque.guvito.site`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 